# Generated by Django 3.1.6 on 2021-08-09 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iot.views.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('monitoring', models.BooleanField(default=False)),
                ('interval', models.IntegerField(null=True)),
                ('activity', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive_monitoring', models.BooleanField(default=False)),
                ('send_message_to_email', models.BooleanField(default=False)),
                ('line_token', models.CharField(blank=True, max_length=100, null=True)),
                ('send_message_to_line', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NumberModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('data', models.FloatField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.devicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=iot.views.models.get_photo_upload_path, verbose_name='Photo')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.devicemodel')),
            ],
        ),
    ]
