# Generated by Django 3.1.6 on 2021-07-27 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='numbermodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.devicemodel'),
        ),
        migrations.AlterField(
            model_name='numbermodel',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.devicemodel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='LD_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='line_token_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mail_status',
            field=models.BooleanField(default=False),
        ),
    ]
