# Generated by Django 3.1.6 on 2021-07-27 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_auto_20210727_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicemodel',
            old_name='device_id',
            new_name='device_token',
        ),
        migrations.RenameField(
            model_name='imagemodel',
            old_name='device_id',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='numbermodel',
            old_name='device_id',
            new_name='device',
        ),
    ]
