# Generated by Django 3.1.6 on 2021-07-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_auto_20210727_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicemodel',
            old_name='interval',
            new_name='alive_interval',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='LD_status',
            new_name='alive_monitoring',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='mail_status',
            new_name='email_status',
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='send_interval',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='threshold',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='turn_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
