# Generated by Django 3.1.6 on 2021-07-27 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_auto_20210727_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicemodel',
            old_name='alive_interval',
            new_name='interval',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='level',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='send_interval',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='threshold',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='turn_on',
        ),
    ]
