# Generated by Django 3.1.6 on 2021-07-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0006_auto_20210727_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='monitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
