# Generated by Django 3.1.6 on 2021-07-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0007_auto_20210727_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='line_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
