# Generated by Django 3.1.6 on 2021-07-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0008_auto_20210727_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_status',
            new_name='send_message_to_email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='line_token_status',
            new_name='send_message_to_line',
        ),
    ]
